### ISSUE TITLE
Feature request: Auto activation

### ISSUE THREAD

**Issue by Xeite** [nokia/PyVenvManage#2]
Hello, I finally got a solution to solve really tedious task to set python intepreters for every project. Many thanks!

Since every virtualenv directories has specific format just as project_dir/.venv or home/.venv, I think automatically activation can be added for those directories. 

How do you think about these feature? I found the solutions using shell script, but it seems to be kind a workaround for me.

Thanks in advance.

**Comment by andrask** [comment]
Hey! Thanks for checking out the plugin.

I usually develop Openstack projects that run tox with many virtualenvs. This is one of the reasons why I had to change frequently and decided to create the plugin.

Could you clarify the automatic activation? Do you mean if a folder is found with a similar name, then it is used automatically? Also, I'd be interested in what shell scripts you use for this purpose. It may be useful in the plugin as well.

**Comment by Xeite** [comment]
@andrask Thanks for comment. To be specific for automatic activation, what I want to do is without "set project venv", just venv setted after opening the project.

By configuration (maybe default is somewhat $project/.venv or something pre-configured), user just can have project within the virtual environment.

My point is similar to 
"https://virtualenvwrapper.readthedocs.io/en/latest/tips.html#automatically-run-workon-when-entering-a-directory".

Script that I said is not found though, if you search with keywords like "auto, virtualenv, pycharm" you can easily find. 

Thanks.

**Comment by andrask** [comment]
Unfortunately, this functionality would be a little hard to implement. It would probably require quite a bit of research and the functionality itself would not be applicable in many cases.

I, for example, run projects with tox and have several venvs at the same time. I wouldn't want the IDE to decide which it is supposed to use to run stuff.

Also, you may have noticed that the `Set project venv` menu item is sometimes not visible, sometimes disabled. These changes are not fully controlled by the plugin. It would require hooks and whatever (I don't know these parts of the Intelli platform) to hang on to the IDE state changes and run some functions when something happens.

So, I am sorry but the "enter the dir and activate venv" kind of functionality is not feasible to implement at the moment. Though we are open to contributions. :)

**Comment by Xeite** [comment]
Thanks for feedback, I got your point. Hope someone can make it. :)

**Comment by andrask** [comment]
Ok, I will close this ticket for now. Feel free to reopen if you have a solution.
