### ISSUE TITLE
When will the 1.1 release turn up in the plugin repo?

### ISSUE THREAD

**Issue by obestwalter** [nokia/PyVenvManage#8]
Hey thanks for releasing the new version :champagne: 

I already installed it from disk as it does not turn up as an update from the repo. Is that a manual step you need to do also? Maybe this could also be handled as part of #4?

**Comment by andrask** [comment]
I submitted it for review yesterday and I guess the automated update will be available once the approval happens. Thanks for sticking with me this long. 👍

**Comment by obestwalter** [comment]
ahh ... it needs to go through review - makes sense :)

> Thanks for sticking with me this long.

I really think it's great! I am recommending it to everyone in combination with [tox](https://tox.readthedocs.io/). It makes it really easy then to switch between different tox environments, so thank you again for creating this!

**Comment by andrask** [comment]
It's up now! :snail:
